name: delete storybook
on:
  pull_request:
    types:
      - closed
jobs:
  delete-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: storybook
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --local user.email github-action@mosmos21.net
          git config --local user.name github-actions
          rm -rf $TARGET_BRANCH
          git add $TARGET_BRANCH
          if [ $(git status --short | wc -l) -ne 0 ]; then git commit -m "Delete storybook @ $TARGET_BRANCH"; fi
          git push
        env:
          TARGET_BRANCH: ${{ steps.branch-name.outputs.branch }}
