name: delete storybook
on:
  pull_request:
    types:
      - closed
jobs:
  delete-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: storybook
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.branch-name.outputs.branch }}
      - run: echo ${{ github.event }}
