name: Build and Deploy
on: pull_request
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mdecoleman/pr-branch-name@1.2.0
        id: branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: output commit hash
        id: commit-hash
        run: echo "::set-output name=result::$(git rev-parse HEAD)"
      - name: build storybook and deploy
        run: |
          npm i && npm run build-storybook
          git config --local user.email github-action@mosmos21.net
          git config --local user.name github-actions
          git fetch origin storybook && git checkout storybook
          rm -rf $TARGET_DIR && mv storybook-static $TARGET_DIR
          git add $TARGET_DIR
          if [ $(git status --short | wc -l) -ne 0 ]; then git commit -m "Deploying to storybook from @ mosmos21/vite-storybook-example@$COMMIT_HASH 🚀"; fi
          git push
        env:
          STORYBOOK_BASE_DIR: /vite-storybook-example/${{ steps.branch-name.outputs.branch }}/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_DIR: ${{ steps.branch-name.outputs.branch }}
          COMMIT_HASH: ${{ steps.commit-hash.outputs.result }}
      - name: comment url on pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const body = `Deploying to ${process.env.STORYBOOK_URL}`;
            
            github.rest.issues.createComment({ issue_number, owner, repo, body });
        env:
          STORYBOOK_URL: https://mosmos21.github.io/vite-storybook-example/${{ steps.branch-name.outputs.branch }}
