name: Build and Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.ref.replace('refs/heads/', ''))
      #- run: npm i && npm run build-storybook
      #- uses: JamesIves/github-pages-deploy-action@v4.3.0
        #with:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #branch: storybook
          #folder: storybook-static
