name: Build and Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: output encoded branch name 🌲
        id: branch-name
        uses: actions/github-script@v6
        with:
          script: return encodeURIComponent(context.ref.replace('refs/heads/', ''))
          result-encoding: string
      - name: build storybook 🔧
        run: npm i && npm run build-storybook
        env:
          STORYBOOK_BASE_DIR: /vite-storybook-example/${{ steps.branch-name.outputs.result }}/
      - uses: actions/checkout@v3
        with:
          ref: storybook
      - run: |
          git branch --current-branch
          git status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
